runtime: php55
api_version: 1

handlers:
    - url: /css
      static_dir: css

    - url: /js
      static_dir: js

    - url: /images
      static_dir: images

    - url: /robots.txt
      static_files: robots.txt

    - url: /.*
      script: index.php
